name: Deploy to Docker Hub and Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/devopsdemo .
        echo ${{ secrets.DOCKERHUB_TOKEN_DEVOPSDEMO }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/devopsdemo

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: josp-devopsdemo
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: ${{ secrets.DOCKERHUB_USERNAME }}/devopsdemo
